<?php
/**
 * Best4Mage - Configurable Product Simple Details
 * @author Best4Mage
 */
?>
<script type="text/x-magento-template" id="tier-prices-template">
<% if(_.size(tierPrices)) { %>
    <table class="prices-tier items">
        <thead>
            <tr>
                <?php if ($block->getAutofill()) : ?>
                    <?php if ($block->getGridTitle()) : ?>
                        <th colspan="3" class="grid-title"><?php echo $block->getGridTitle(); ?></th>
                        <th><span class="tier-qty-reset" title="<%= $t('Reset') %>">&nbsp;</span></th>
                    <?php else : ?>
                        <th colspan="4"><span class="tier-qty-reset">&nbsp;</span></th>
                    <?php endif;?>
                <?php else : ?>
                    <?php if ($block->getGridTitle()) : ?>
                        <th colspan="3" class="grid-title"><?php echo $block->getGridTitle(); ?></th>
                    <?php endif;?>
                <?php endif;?>
            </tr>
            <tr class="text-center">
                <?php if ($block->getAutofill()) : ?>
                    <th><%= $t('Select') %></th>
                <?php endif;?>
                <th><%= $t('Qty') %></th>
                <th><%= $t('Price Per Unit') %></th>
                <th><%= $t('Save') %></th>
            </tr>
        </thead>
        <tbody>
            <% _.each(tierPrices, function(item, key) { %>
            <%  var priceStr = '<span class="price-container price-tier_price">'
                    + '<span data-price-amount="' + priceUtils.formatPrice(item.price, currencyFormat) + '"'
                    + ' data-price-type=""' + ' class="price-wrapper ">'
                    + '<span class="price">' + priceUtils.formatPrice(item.price, currencyFormat) + '</span>'
                    + '</span>'
                + '</span>'; %>
            <tr class="item">
                <?php if ($block->getAutofill()) : ?>
                    <td>
                        <input type="radio" name="tier-radio" class="tier-radio" data-qty="<%= item.qty %>"/>
                    </td>
                <?php endif;?>
                <td><%= item.qty %></td>
                <td><%= priceStr %></td>
                <td><%= item.percentage %>%</td>
            </tr>
            <% }); %>
        </tbody>
    </table>
<% } %>
</script>
<div data-role="tier-price-block"></div>

<?php if ($block->getAutofill()) : ?>
    <script type="text/javascript">
        require(['jquery'], function($) {
            $(document).on('click', 'input.tier-radio', function(){
                if($(this).attr('checked')) {
                    $('#qty').val($(this).data('qty'));
                }
            });

            $(document).on('click', '.tier-qty-reset', function(){
                $('#qty').val(1);
                $('input.tier-radio').attr('checked',false);
            });
        });
    </script>
<?php endif;?>
