<?php
/**
 * Best4Mage - Configurable Product Simple Details
 * @author Best4Mage
 */
?>

<?php
/** @var \Magento\Catalog\Pricing\Render\PriceBox $block */

/** @var \Magento\Catalog\Pricing\Price\TierPrice $tierPriceModel */
$tierPriceModel = $block->getPrice();
$tierPrices = $tierPriceModel->getTierPriceList();
$product = $block->getSaleableItem();
?>
<?php if (count($tierPrices)) : ?>
    <table class="prices-tier items">
        <thead>
            <tr>
                <?php if ($block->getAutofill()) : ?>
                    <?php if ($block->getGridTitle()) : ?>
                        <th colspan="3" class="grid-title"><?php echo $block->getGridTitle(); ?></th>
                        <th><span class="tier-qty-reset" title="<?php echo __('Reset') ?>">&nbsp;</span></th>
                    <?php else : ?>
                        <th colspan="4"><span class="tier-qty-reset">&nbsp;</span></th>
                    <?php endif;?>
                <?php else : ?>
                    <?php if ($block->getGridTitle()) : ?>
                        <th colspan="3" class="grid-title"><?php echo $block->getGridTitle(); ?></th>
                    <?php endif;?>
                <?php endif;?>
            </tr>
            <tr class="text-center">
                <?php if ($block->getAutofill()) : ?>
                    <th><?php echo __('Select') ?></th>
                <?php endif;?>
                <th><?php echo __('Qty') ?></th>
                <th><?php echo __('Price Per Unit') ?></th>
                <th><?php echo __('Save') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($tierPrices as $index => $price) : ?>
                <tr class="item">
                    <?php if ($block->getAutofill()) : ?>
                        <td>
                            <input type="radio" name="tier-radio" class="tier-radio" data-qty="<%= item.qty %>"/>
                        </td>
                    <?php endif;?>
                    <?php
                        $priceAmountBlock = $block->renderAmount(
                            $price['price'],
                            [
                                'price_id'          => $index,
                                'id_suffix'         => '-' . $index,
                                'include_container' => true,
                                'zone' => \Magento\Framework\Pricing\Render::ZONE_ITEM_OPTION
                            ]
                        );
                    ?>
                    <td><?php $price['price_qty'] ?></td>
                    <td><?php $priceAmountBlock ?></td>
                    <td><?php $tierPriceModel->getSavePercent($price['price']) ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <?php if ($block->getAutofill()) : ?>
        <script type="text/javascript">
            require(['jquery'], function($) {
                $(document).on('click', 'input.tier-radio', function(){
                    if($(this).attr('checked')) {
                        $('#qty').val($(this).data('qty'));
                    }
                });

                $(document).on('click', '.tier-qty-reset', function(){
                    $('#qty').val(1);
                    $('input.tier-radio').attr('checked',false);
                });
            });
        </script>
    <?php endif;?>

<?php endif; ?>
