<?php
    /** @var $block \Magento\Swatches\Block\Product\Renderer\Listing\Configurable */
    $productId = $block->getProduct()->getId();
    $currentCat = $block->getCurrentCategory();
    $isCPSDEnabledCat = $block->getCpsdHelper()->isEnableCat($currentCat);
    $isSwitchPrice = $block->getCpsdHelper()->isSwitchPrice($currentCat); //print_r($isSwitchPrice); die;
?>
<div class="swatch-opt-<?= /* @escapeNotVerified */ $productId ?>" 
     data-role="swatch-option-<?= /* @escapeNotVerified */ $productId ?>"></div>

<script type="text/x-magento-init">
    {
        "[data-role=swatch-option-<?= /* @escapeNotVerified */ $productId ?>]": {
            "Lightweight_CpsdRefactored/js/list/cpsd": {
                "selectorProduct": ".product-item-details",
                "onlySwatches": <?php echo $isSwitchPrice ? '0' : '1' ?>,
                "enableControlLabel": false,
                "numberToShow": <?= /* @escapeNotVerified */ $block->getNumberSwatchesPerProduct(); ?>,
                "jsonConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig(); ?>,
                "jsonSwatchConfig": <?= /* @escapeNotVerified */ $block->getJsonSwatchConfig(); ?>,
                "mediaCallback": "<?= /* @escapeNotVerified */ $block->getMediaCallback() ?>",
                "isCPSDEnabled": <?php echo (int)$isCPSDEnabledCat; ?>,
                "tierPriceTemplateSelector": "#cpsd-tier-price-template",
                "tierPriceBlockSelector": ".tier-price-box",
                "jsonProductData": <?php echo $block->getAllProductsData(); ?>,
                "productNameSelector": "<?php echo $block->getCpsdHelper()->getListNameSelector(); ?>",
                "productUrlSelector": <?php echo $block->jsonEncode($block->getCpsdHelper()->getListUrlSelector()); ?>
            }
        }
    }
</script>

<?php if (version_compare($block->getCpsdHelper()->getMagentoVersion(), '2.2.0', '>=')) : ?>
<script type="text/x-magento-init">
    {
        "[data-role=priceBox][data-price-box=product-id-<?= /* @escapeNotVerified */ $productId ?>]": {
            "priceBox": {
                "priceConfig": {
                    "priceFormat": <?= /* @escapeNotVerified */ $block->getPriceFormatJson(); ?>,
                    "prices": <?= /* @escapeNotVerified */ $block->getPricesJson(); ?>
                }
            }
        }
    }
</script>
<?php else : ?>
<script type="text/javascript">
    require([
        'jquery',
        'priceBox'
    ], function($){
        var priceBox = $("[data-role=priceBox][data-price-box=product-id-<?php /* @escapeNotVerified */ echo $productId ?>]");
        priceBox.priceBox({'priceConfig': <?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>});
    });
</script>
<?php endif; ?>
